const modelosAutos = [
    {
        id: 1,
        modeloAuto: 'TIGGO 3',
        tipoAuto: 'SUV',
        anioAuto: 2020,
        precioLista: 10990,
        precioAuto: 8990,
        marca: 'Chery',
    },

    {
        id: 2,
        modeloAuto: 'DURANGO',
        tipoAuto: 'SUV',
        anioAuto: 2020,
        precioLista: 20990,
        precioAuto: 16720,
        marca: 'Dodge',
    },

    {
        id: 3,
        modeloAuto: 'AIRCROSS',
        tipoAuto: 'SUV',
        anioAuto: 2020,
        precioLista: 21200,
        precioAuto: 17200,
        marca: 'Citroen',
    },

    {
        id: 4,
        modeloAuto: 'RIDGELINE',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2020,
        precioLista:15000,
        precioAuto: 9890,
        marca: 'Honda',
    },

    {
        id: 5,
        modeloAuto: 'WRANGLER',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2020,
        precioAuto: 11990,
        precioLista:16990,
        marca: 'Jeep',
    },

    {
        id: 6,
        modeloAuto: 'GLADIATOR',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2019,
        precioLista:18990,
        precioAuto: 11990,
        marca: 'Jeep',
    },

    {
        id: 7,
        modeloAuto: 'C-ELYSEE',
        tipoAuto: 'SEDAN',
        anioAuto: 2021,
        precioLista: 10990,
        precioAuto: 8890,
        marca: 'Citroen',
    },

    {
        id: 8,
        modeloAuto: 'CRONOS',
        tipoAuto: 'SEDAN',
        anioAuto: 2021,
        precioLista:12990,
        precioAuto: 9960,
        marca: 'Fiat',
    },

    {
        id: 9,
        modeloAuto: 'ACCORD',
        tipoAuto: 'SEDAN',
        anioAuto: 2022,
        precioLista: 12990,
        precioAuto: 10990,
        marca: 'Honda',
    },
    {
        id: 10,
        modeloAuto: 'TRUCK DC',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2019,
        precioLista: 9151,
        precioAuto: 7842,
        marca: 'Dfsk',
    },
    {
        id: 11,
        modeloAuto: 'VIGUS PLUS',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2023,
        precioLista: 19504,
        precioAuto: 18314,
        marca: 'JMC',
    },
    {
        id: 12,
        modeloAuto: 'TIGGO 7',
        tipoAuto: 'SUV',
        anioAuto: 2023,
        precioLista: 19990,
        precioAuto: 16490,
        marca: 'Chery',
    },
    {
        id: 13,
        modeloAuto: 'CORLAY',
        tipoAuto: 'SUV',
        anioAuto: 2021,
        precioLista: 16990,
        precioAuto: 14990,
        marca: 'Geely',
    },
    {
        id: 14,
        modeloAuto: 'CIVIC',
        tipoAuto: 'SEDAN',
        anioAuto: 2022,
        precioLista: 26390,
        precioAuto: 25490,
        marca: 'Honda',
    },
    {
        id: 15,
        modeloAuto: 'CERATO 5',
        tipoAuto: 'SEDAN',
        anioAuto: 2022,
        precioLista: 23490,
        precioAuto: 22990,
        marca: 'Kia Motors',
    },
    {
        id: 16,
        modeloAuto: 'MG3',
        tipoAuto: 'SEDAN',
        anioAuto: 2023,
        precioLista: 11390,
        precioAuto: 10890,
        marca: 'Mg',
    },
    {
        id: 17,
        modeloAuto: 'NEW MUSSO GRAND',
        tipoAuto: 'CAMIONETA',
        anioAuto: 2021,
        precioLista: 23430,
        precioAuto: 22630,
        marca: 'Ssangyong',
    },
    {
        id: 18,
        modeloAuto: 'ECLIPSE CROSS',
        tipoAuto: 'SUV',
        anioAuto: 2023,
        precioLista: 22990,
        precioAuto: 21990,
        marca: 'Mitsubishi',

    },
];